### ISSUE TITLE
Data Issue: US Equities Missing 23RD FEB 2021 intra-day OHLC data - multiple time frames and tickers

### ISSUE THREAD

**Issue by elenaelizebeth** [finnhubio/Finnhub-API#408]
Missing Data in intraday OHLC for (all) US Equities : Candles missing between 14:40 UTC and 19:10 UTC 23rd Feb 2021

E.G the following query:
https://finnhub.io/api/v1/stock/candle?symbol=ADBE&resolution=5&from=1614038400&to=1614643200&token=

yields:

timestamps : [1614072300,1614075900,1614079200,1614088800,**1614090600**,**1614090900**,**1614107400**,1614107700,1614108000,1614108300,1614108600,1614108900,1614109200,1614109500,1614109800,1614110100,1614110400,1614110700,1614111000,1614111300,1614111600,1614111900,1614112200,1614112500,1614112800,1614113100,1614113400,1614113700,1614114000,1614172800,1614174600,1614176700,1614177000,1614177300,1614177600,1614177900,1614178200,1614178500,1614178800,1614179100,1614179400,1614179700,1614180000,1614180300,1614180600,1614180900,1614181500,1614181800,1614182100,1614182400,1614182700,1614183000,1614183300,1614183600,1614183900,1614184200,1614184500,1614184800,1614185100,1614185400,1614185700,1614186000,1614186300,1614186600,1614186900,1614187200,1614187500,1614187800,1614188100,1614188400,1614188700,1614189000,1614189300,1614189600,1614189900,1614190200,1614190500,1614190800,1614191100,1614191400,1614191700,1614192000,1614192300,1614192600,1614192900,1614193200,1614193500,1614193800,1614194100,1614194400,1614194700,1614195000,1614195300,1614195600,1614195900,1614196200,1614196500,1614196800,1614197100,1614197400,1614197700,1614198000,1614198300,1614198600,1614198900,1614199200,1614199500,1614199800,1614200100,1614200400,1614206100,1614206400,1614208800]

In UTC the above highlighted times are 14:30, 14:35 and then 19:10.

Noticed among many time frames e.g 15M
https://finnhub.io/api/v1/stock/candle?symbol=ADBE&resolution=15&from=1614038400&to=1614232683&
 timestamps:

[1614088800,**1614090600,1614107700,**1614108600,1614109500,1614110400,1614111300,1614112200,1614113100,1614114000,1614177000,1614177900,1614178800,1614179700,1614180600,1614181500,1614182400,1614183300,1614184200,1614185100,1614186000,1614186900,1614187800,1614188700,1614189600,1614190500,1614191400,1614192300,1614193200,1614194100,1614195000,1614195900,1614196800,1614197700,1614198600,1614199500,1614200400,1614202200,1614203100,1614204900,1614205800,1614208500]

**Comment by shjoshi95** [comment]
I noticed a similar issue for Feb 22 (SPY for example returns no 60-minute OHLC candles that day), and most data is missing from Feb 23 as well.

**Comment by finnhubio** [comment]
The issue has been corrected now. Can you guys please try again ?

**Comment by shjoshi95** [comment]
Seems the Issue is slightly improved, but it still happening. Here is some recent 60min data for MSFT, where timestamps are UTC hours. Seems the issue is still happening, as even some rows from the past two days are occasionally missing. I have noted all the missing rows this week below. Can you please investigate? This is a pretty major bug to have missing rows like this...

**[Missing 2021-02-22 14:00:00 row]**
2021-02-22 15:00:00   234.210   236.55  233.81  236.420  ok   5719844.0
2021-02-22 16:00:00   232.730   235.01  232.54  234.190  ok   5547744.0
2021-02-22 17:00:00   234.190   234.57  232.40  232.750  ok   3403194.0
2021-02-22 18:00:00   235.530   235.65  233.94  234.190  ok   2039399.0
**[Missing 2021-02-22 19:00:00 row]**
2021-02-22 20:00:00   234.600   235.41  234.06  235.330  ok  11780262.0
2021-02-23 14:00:00   230.720   234.70  228.73  230.750  ok   6369413.0
**[Missing 2021-02-23 15:00:00 row]**
**[Missing 2021-02-23 16:00:00 row]**
2021-02-23 17:00:00   230.030   232.55  229.99  232.160  ok   2860865.0
2021-02-23 18:00:00   232.210   232.68  229.83  230.040  ok   1974129.0
2021-02-23 19:00:00   232.990   233.04  231.80  232.200  ok   2125357.0
2021-02-23 20:00:00   233.270   234.83  232.04  232.990  ok   4663303.0
2021-02-24 14:00:00   231.070   234.96  229.52  230.520  ok   3436729.0
**[Missing 2021-02-24 15:00:00 row]**
2021-02-24 16:00:00   232.000   232.29  230.94  231.080  ok   2718326.0
2021-02-24 17:00:00   233.000   233.05  231.95  232.010  ok   2293316.0
2021-02-24 18:00:00   234.110   234.18  232.26  233.020  ok   2026073.0
2021-02-24 19:00:00   233.720   234.18  233.47  234.110  ok    988798.0
**[Missing 2021-02-24 20:00:00 row]**
2021-02-25 14:00:00   234.200   234.57  231.65  232.700  ok   2740102.0
2021-02-25 15:00:00   233.110   234.23  231.59  234.200  ok   4033644.0
2021-02-25 16:00:00   230.620   234.10  230.48  233.080  ok   4205585.0
2021-02-25 17:00:00   229.710   231.25  229.68  230.630  ok   3649311.0
2021-02-25 18:00:00   230.650   230.91  228.50  229.440  ok   4581411.0
2021-02-25 19:00:00   230.170   232.26  230.15  230.630  ok   1778307.0
**[Missing 2021-02-25 20:00:00 row]**
2021-02-26 14:00:00   232.530   232.60  227.13  231.680  ok   1758107.0
2021-02-26 15:00:00   232.940   233.31  229.54  231.210  ok   6383034.0
2021-02-26 16:00:00   231.500   233.51  231.41  232.950  ok   1438826.0
